### PR TITLE
Hello Microverse Project Pull Request

### PR DESCRIPTION
**Pull request by May126-sone**
This is a simple html and css project

### CODE REVIEW

**Comment by DanielAD10** [comment]
Please kindly finish your Linter installing...
I think there are some issue in your style.css 

If you don't know how to fix it, you can follow the steps in this [](https://github.com/microverseinc/linters-config/tree/master/html-css)

**Review by DanielAD10 — CHANGES_REQUESTED** [review]
Please kindly finish your Linter installing...
I think there are some issue in your style.css

If you don't know how to fix it, you can follow the steps in this https://github.com/microverseinc/linters-config/tree/master/html-css

**Comment by May126-sone** [comment]
> Please kindly finish your Linter installing... I think there are some issue in your style.css
> 
> If you don't know how to fix it, you can follow the steps in this https://github.com/microverseinc/linters-config/tree/master/html-css

Thank you for reviewing. I will check, right now.

**Review by DanielAD10 — CHANGES_REQUESTED** [review]
###  STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @K-mone  👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

close lady

## Highlights 💯 
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
- Linter errors

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by K0ppai** [comment]
# Status: INVALID REVIEW REQUEST 🚫 


# Hi @May126-sone 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- Kindly make sure that all linter checks are green so that I can proceed with the review process.

## Optional Changes ♻️ 

- Kindly check out this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for how to create a professional pull request and commits.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by May126-sone** [comment]
All linter checks are green and could you check it again, please?

**Comment by May126-sone** [comment]
> # Status: INVALID REVIEW REQUEST 🚫
>  [ 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f52657944344f64526948654c4443526145502f67697068792e676966 ](https://camo.githubusercontent.com/4187074f6b8307d11768c326133ea198a73743e5b747571572effcf028fa3f59/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f52657944344f64526948654c4443526145502f67697068792e676966) [ ](https://camo.githubusercontent.com/4187074f6b8307d11768c326133ea198a73743e5b747571572effcf028fa3f59/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f52657944344f64526948654c4443526145502f67697068792e676966)
> 
> # Hi @May126-sone 👋,
> You're doing a good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * Kindly make sure that all linter checks are green so that I can proceed with the review process.
> 
> ## Optional Changes ♻️
> * Kindly check out this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for how to create a professional pull request and commits.
> 
> Cheers, and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**Comment by May126-sone** [comment]
@K0ppai 
All linter checks are green and could you check it again, please?

**Review by K0ppai — COMMENTED** [review]
## Hi @May126-sone, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Must Do In Next Projects

- Kindly update `README.md` file using the [template](https://github.com/microverseinc/readme-template) given in the project requirement in your future projects. Considering the simplicity of this project, I'll overlook this matter in this one.

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by May126-sone** [comment]
@K0ppai 
Thank you for reviewing and I am trying my best to update README file in the portfolio project.

**Pull request merged**
